### ISSUE TITLE
build failed: unresolved references

### ISSUE THREAD

**Issue by mrolappe** [ftomassetti/kanvas#1]
hi federico,

unfortunately the build fails for me, supposedly due to missing dependencies/private libraries.

...
:assemble UP-TO-DATE
:kanvas-core:compileKotlin
e: /opt/volumes/swentw/kanvas/kanvas-core/src/main/kotlin/LanguageSupport.kt: (3, 22): Unresolved reference: antlr
e: /opt/volumes/swentw/kanvas/kanvas-core/src/main/kotlin/LanguageSupport.kt: (63, 56): Unresolved reference: None
:kanvas-core:compileKotlin FAILED

**Comment by ftomassetti** [comment]
Hi Marco, I am sorry to hear that and thankful for your report. I should start by setting up Travis ASAP (#2). 

Have you tried running `./gradlew generateGrammarSource` ?

**Comment by mrolappe** [comment]
hi federico,

no worries. I had not tried the `./gradlew generateGrammarSource`.

I did now and it seems to proceed further than before. now it fails at a different point in the build (doing `gradlew build`:

:kanvas-sandy:classes
:kanvas-sandy:jar
:kanvas-sandy:assemble
:kanvas-sandy:compileTestKotlin
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-test/1.0.6/kotlin-test-1.0.6.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-test-parent/1.0.6/kotlin-test-parent-1.0.6.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-test-junit/1.0.6/kotlin-test-junit-1.0.6.pom
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-test/1.0.6/kotlin-test-1.0.6.jar
Download https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-test-junit/1.0.6/kotlin-test-junit-1.0.6.jar
e: /opt/volumes/swentw/kanvas/kanvas-sandy/src/test/kotlin/CompletionTest.kt: (15, 9): Type inference failed. The value of the type parameter T should be mentioned in input types (argument types, receiver type or expected type). Try to specify it explicitly.
e: /opt/volumes/swentw/kanvas/kanvas-sandy/src/test/kotlin/CompletionTest.kt: (21, 9): Type inference failed. The value of the type parameter T should be mentioned in input types (argument types, receiver type or expected type). Try to specify it explicitly.
e: /opt/volumes/swentw/kanvas/kanvas-sandy/src/test/kotlin/CompletionTest.kt: (27, 9): Type inference failed. The value of the type parameter T should be mentioned in input types (argument types, receiver type or expected type). Try to specify it explicitly.
e: /opt/volumes/swentw/kanvas/kanvas-sandy/src/test/kotlin/CompletionTest.kt: (34, 9): Type inference failed. The value of the type parameter T should be mentioned in input types (argument types, receiver type or expected type). Try to specify it explicitly.
e: /opt/volumes/swentw/kanvas/kanvas-sandy/src/test/kotlin/CompletionTest.kt: (41, 9): Type inference failed. The value of the type parameter T should be mentioned in input types (argument types, receiver type or expected type). Try to specify it explicitly.
:kanvas-sandy:compileTestKotlin FAILED

**Comment by ftomassetti** [comment]
hi @mrolappe I forgot to refactor some tests. They should work now and hopefully Travis will help catch such errors in the future
