### ISSUE TITLE
Autocompletion for sandy stopped to work after complex expression in parentesis

### ISSUE THREAD

**Issue by eschava** [ftomassetti/kanvas#4]
Expression
**var a=(1**
has suggestions 
),*,+,-,/
but expression
**var a=(1+1**
should have same suggestions instead if has only
*,+,-,/
(without closing parenthesis)

I think it's related to handling of StarLoopbackState somehow.

**Comment by eschava** [comment]
I've added couple of unit tests to CompletionTest.kt:

    @test fun incompleteParenthesis() {
        val code = "var a = (1"
        assertEquals(setOf(TokenTypeImpl(SandyLexer.RPAREN), TokenTypeImpl(SandyLexer.PLUS), TokenTypeImpl(SandyLexer.MINUS), TokenTypeImpl(SandyLexer.DIVISION), TokenTypeImpl(SandyLexer.ASTERISK)),
                AntlrAutoCompletionSuggester(SandyParser.ruleNames,SandyLexer.VOCABULARY,SandyParser._ATN)
                .suggestions(EditorContextImpl(code, sandyLanguageSupport.antlrLexerFactory)).proposals)
    }

    @test fun incompleteComplexParenthesis() {
        val code = "var a = (1+1"
        assertEquals(setOf(TokenTypeImpl(SandyLexer.RPAREN), TokenTypeImpl(SandyLexer.PLUS), TokenTypeImpl(SandyLexer.MINUS), TokenTypeImpl(SandyLexer.DIVISION), TokenTypeImpl(SandyLexer.ASTERISK)),
                AntlrAutoCompletionSuggester(SandyParser.ruleNames,SandyLexer.VOCABULARY,SandyParser._ATN)
                .suggestions(EditorContextImpl(code, sandyLanguageSupport.antlrLexerFactory)).proposals)
    }

now second test fails

**Comment by ftomassetti** [comment]
Thank you for reporting this. The auto-completion code is a bit tricky, and more tests to cover it will definitely help

**Comment by eschava** [comment]
Is there any chance to have it fixed?

**Comment by ftomassetti** [comment]
Yes, I plan to do this in the following weeks. I could accept a PR sooner

**Comment by eschava** [comment]
Have you finished with the fix?

**Comment by ftomassetti** [comment]
No, I was hoping to get a PR, then I was kept busy by other open-source projects

**Comment by ftomassetti** [comment]
I have added the two tests you suggested in a separate branch. The first one seems to pass now, while the second one fails.

**Comment by ftomassetti** [comment]
Now it should work. It took a while because I aimed to a significant refactoring, creating a separate library for autocompletion which is integrated into kanvas but can be used also separately.
Sorry it took so long.

**Comment by eschava** [comment]
Thanks a lot!

**Comment by ftomassetti** [comment]
Thanks to you for reporting the issue and for your patience. I will be more reactive in the future!
