### ISSUE TITLE
Problem running the tool

### ISSUE THREAD

**Issue by AlessandroCaste** [ftomassetti/kanvas#8]
Hi! Running the kanvas.kt (Intellij, jdk 1.8) returns a black editor where I can't write anything.
I'm still wrapping my mind around Kotlin and swing, so maybe am I missing something?
Thanks for all your guides and hard work!

![image](https://user-images.githubusercontent.com/32411739/54196509-ebfb4280-44c1-11e9-9636-c383f5a85c2d.png)

![image](https://user-images.githubusercontent.com/32411739/54196867-bdca3280-44c2-11e9-8c4f-dbce2589487d.png)

**Comment by AlessandroCaste** [comment]
I was generating java classes using Intellij ANTLR plugin (4.7.2). Changing the runtime version in build.gradle solves the issue.

**Comment by ftomassetti** [comment]
Nice. I thought the issue was just that you needed to create a file before being able to write on it
